[project]
name = "custom-keybinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "auto-py-to-exe>=2.46.0",
    "keyboard>=0.13.5",
    "rich>=13.9.4",
]
